### ISSUE TITLE
Roadmap checkboxes

### ISSUE THREAD

**Issue by ccokee** [ccokee/rbpi-ansible-cluster-k8s#1]
- # Remainings
- ## Project config:
   - [ ] Define project tree.
- ## Cluster configuration:
   - [ ] Cluster-prep:
      - [ ] Hostname configuration.
      - [ ] /etc/hosts configuration.
   - [ ] Disk-prep:
      - [ ] Find empty block device.
      - [ ] Zapp block device.
      - [ ] Clean block device with dd.
   - [ ] Ufw:
       - [ ] Setup rules for interfaces.
       - [ ] Setup rules for ports.
       - [ ] Setup general DROP policy. 
- ## Deployments:
   - [ ] Rook: 
       - [ ] Create cephfs cluster through Helm chart in SAN nodes.
       - [ ] Wait until fully deployed.
   - [ ] Cert-manager:
      - [ ] Deployment through Helm chart.
      - [ ] ACME issuer.
      - [ ] Wait until fully deployed.
      - [ ] Issue Ethereum dashboard certificate.
      - [ ] Issue Ipfs certificate.
   - [ ] Ethereum:
      - [ ] Create manifests.
      - [ ] Create Helm chart.
      - [ ] Deployment through Helm chart.
      - [ ] Wait until fully deployed.
   - [ ] Ipfs:
      - [ ] Create manifests.
      - [ ] Create Helm chart.
      - [ ] Deployment through Helm chart.
      - [ ] Wait until fully deployed.
   - [ ] Metal-lb: 
      - [ ] Deployment through Helm chart.
      - [ ] Configure private ip range for cluster services in defaults.
      - [ ] Wait for external ips and register them.
   - [ ] Ingress:
      - [ ] Create manifests. 
      - [ ] Deployment.
      - [ ] Configure Ethereum dashboard endpoint with certificate.
      - [ ] Configure Ethereum api endpoint for dApp deployment.
      - [ ] Configure Ipfs endpoint with certificate.
- ## Screen node configuration:
   - [ ] Xdeps: 
       - [ ] Install dependencies for screen node.
   - [ ] Lightdm: 
      - [ ] Set system service in screen node.
      - [ ] Auto login for ubuntu user in screen node.
   - [ ] Openbox: 
       - [ ] Set the startup script (Only ethereum dashboard).
- ## Research:
   - [ ] Add geolocation for Ethereum miners.
   - [ ] IPFS cluster deployment.
